var mongoose = require('mongoose');
var Schema = mongoose.Schema;

//Schema is defined to store employees information @MongoDB
var employeeSchema = new Schema({
	firstName: { type: String, required: true }, //Fisrt Name is required
	secondName: { type: String }, //Second Name is optional
	fatherName: { type: String, required: true }, //Father or Last Name is required
	motherName: { type: String }, //Mother Last Name is optional
	//employeeId: Schema.Types.ObjectId, //Employee ID is generated by MongoDB
	birthDate: { type: Date, required: true }, //Birth Date is required
	age: { type: Number }, //Employee age
	startDate: { type: Date, default: Date.now }, //Date when a new employee is hired and created on LMS
	endDate: { type: Date }, //Fecha en que el empleado deja de laborar con la compañía
	isActive: { type: Boolean, default: true }, //Bandera que nos permite saber si empleado está "En Activo" o bien "Inactivo"
	plant: { type: String }, //La planta o tienda a la que el empleado pertenece
	dept: [{ type: String, ref: 'Department' }], //Departamento(s) al que el empleado es asignado
	weekSchedule: [{ type: Date, ref: 'Schedule' }], //Es la asiganación recomendada al empleado, por el algorimo de Axity
	role: [{ type: Number, ref: 'Role' }], //Rol, puesto u oficio al que el empleado es asignado
	status: [{ type: String, ref: 'Status' }] //Estatus del empleado: Activo, Vacaciones, Ausencia por Enfermedad, Incapacidad, Ausencia Injustificada
});


module.exports = mongoose.model('Employee',employeeSchema);
